# [metadata]
# name = "carbonfox"
# author = "wjohnsto"
# origin_url = "https://github.com/EdenEast/nightfox.nvim"

"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](os_bg)\
$os\
$username\
[](bg:dir_bg fg:os_bg)\
$directory\
[](fg:dir_bg bg:git_bg)\
$git_branch\
$git_status\
[](fg:git_bg bg:lang_bg)\
$nodejs\
$rust\
$golang\
[](fg:lang_bg bg:background)\
\n$character"""

palette = "carbonfox"
# palette = "dawnfox"
# palette = "dayfox"
# palette = "duskfox"
# palette = "nightfox"
# palette = "nordfox"
# palette = "terafox"

[palettes.carbonfox]
red = "#ee5396"
green = "#25be6a"
purple = "#be95ff"
yellow = "#08bdba"
os_bg = "#7b7c7e"
os_fg = "#0c0c0c"
dir_bg = "#25be6a"
dir_fg = "#161616"
git_bg = "#08bdba"
git_fg = "#252525"
lang_bg = "#78a9ff"
lang_fg = "#353535"

[palettes.dawnfox]
red = "#b4637a"
green = "#618774"
purple = "#907aa9"
yellow = "#ea9d34"
os_bg = "#a8a3b3"
os_fg = "#ebe5df"
dir_bg = "#618774"
dir_fg = "#faf4ed"
git_bg = "#ea9d34"
git_fg = "#ebe0df"
lang_bg = "#286983"
lang_fg = "#ebdfe4"

[palettes.dayfox]
red = "#a5222f"
green = "#396847"
purple = "#6e33ce"
yellow = "#ac5402"
os_bg = "#824d5b"
os_fg = "#e4dcd4"
dir_bg = "#396847"
dir_fg = "#f6f2ee"
git_bg = "#ac5402"
git_fg = "#dbd1dd"
lang_bg = "#2848a9"
lang_fg = "#d3c7bb"

[palettes.duskfox]
red = "#eb6f92"
green = "#a3be8c"
purple = "#c4a7e7"
yellow = "#f6c177"
os_bg = "#6e6a86"
os_fg = "#191726"
dir_bg = "#a3be8c"
dir_fg = "#232136"
git_bg = "#f6c177"
git_fg = "#2d2a45"
lang_bg = "#569fba"
lang_fg = "#373354"

[palettes.nightfox]
red = "#c94f6d"
green = "#81b29a"
purple = "#9d79d6"
yellow = "#dbc074"
os_bg = "#71839b"
os_fg = "#131a24"
dir_bg = "#81b29a"
dir_fg = "#192330"
git_bg = "#dbc074"
git_fg = "#212e3f"
lang_bg = "#719cd6"
lang_fg = "#29394f"

[palettes.nordfox]
red = "#bf616a"
green = "#a3be8c"
purple = "#b48ead"
yellow = "#ebcb8b"
os_bg = "#7e8188"
os_fg = "#232831"
dir_bg = "#a3be8c"
dir_fg = "#2e3440"
git_bg = "#ebcb8b"
git_fg = "#39404f"
lang_bg = "#81a1c1"
lang_fg = "#444c5e"

[palettes.terafox]
red = "#e85c51"
green = "#7aa4a1"
purple = "#ad5c7c"
yellow = "#fda47f"
os_bg = "#587b7b"
os_fg = "#0f1c1e"
dir_bg = "#7aa4a1"
dir_fg = "#152528"
git_bg = "#fda47f"
git_fg = "#1d3337"
lang_bg = "#5a93aa"
lang_fg = "#254147"

[os]
disabled = false
style = "bg:os_bg fg:os_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = " 󰣭 "
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:os_bg fg:os_fg"
style_root = "bg:os_bg fg:os_fg"
format = "[ $user ]($style)"

[directory]
style = "fg:dir_fg bg:dir_bg"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"src" = " "

[git_branch]
symbol = ""
style = "bg:git_bg"
format = '[[ $symbol $branch ](fg:git_fg bg:git_bg)]($style)'

[git_status]
style = "bg:git_bg"
format = '[[($all_status$ahead_behind )](fg:git_fg bg:git_bg)]($style)'

[nodejs]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[c]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[rust]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[golang]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[php]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[java]
symbol = " "
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[kotlin]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[haskell]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[python]
symbol = ""
style = "bg:lang_bg"
format = '[[ $symbol( $version) ](fg:lang_fg bg:lang_bg)]($style)'

[character]
disabled = false
success_symbol = '[󰁔](bold fg:green)'
error_symbol = '[󰁔](bold fg:red)'
vimcmd_symbol = '[󰁍](bold fg:green)'
vimcmd_replace_one_symbol = '[󰁍](bold fg:purple)'
vimcmd_replace_symbol = '[󰁍](bold fg:purple)'
vimcmd_visual_symbol = '[󰁍](bold fg:yellow)'

